puts "The students of my cohort at Makers Academy"
puts "Abraham Thomas"
puts "Andy Parton"
puts "Damien Hogan"
puts "Dean Bryen"
puts "Dharmesh Raithatha"
puts "Enrique Comba Riepenhausen"
puts "Joan Senent"
puts "Katrina Harradine"
puts "John Damico"
puts "Jorja Tracy Hung"
puts "Kiy-Hong Tang"
puts "Peter Saxton"
puts "Peter Hitchcock"
puts "Samantha Harris"
puts "Yvette Cook"
puts "David Thompson"
print "Overall, we have "
print 16
puts " great students"
